"""initial schema

Revision ID: af8e44648542
Revises: 
Create Date: 2026-07-20 11:28:44.514296

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'af8e44648542'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('equity_snapshots',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('equity_usd', sa.Float(), nullable=False),
    sa.Column('cash_usd', sa.Float(), nullable=False),
    sa.Column('exposure_usd', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('risk_scores',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('runs',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('environment', sa.String(length=16), nullable=False),
    sa.Column('summary_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('settings_audit',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bot_positions',
    sa.Column('etoro_position_id', sa.BigInteger(), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('amount_usd', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sector', sa.String(length=64), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('close_price', sa.Float(), nullable=True),
    sa.Column('realized_pnl_usd', sa.Float(), nullable=True),
    sa.Column('close_reason', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ),
    sa.PrimaryKeyConstraint('etoro_position_id')
    )
    op.create_index('ix_bot_positions_closed_at', 'bot_positions', ['closed_at'], unique=False)
    op.create_table('decisions',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_decisions_run_id', 'decisions', ['run_id'], unique=False)
    op.create_table('executions',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('amount_usd', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('execution_price', sa.Float(), nullable=True),
    sa.Column('etoro_position_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_executions_created_at', 'executions', ['created_at'], unique=False)
    op.create_index('ix_executions_run_id', 'executions', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_executions_run_id', table_name='executions')
    op.drop_index('ix_executions_created_at', table_name='executions')
    op.drop_table('executions')
    op.drop_index('ix_decisions_run_id', table_name='decisions')
    op.drop_table('decisions')
    op.drop_index('ix_bot_positions_closed_at', table_name='bot_positions')
    op.drop_table('bot_positions')
    op.drop_table('settings_audit')
    op.drop_table('runs')
    op.drop_table('risk_scores')
    op.drop_table('equity_snapshots')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
