"""drop mode column from runs

Revision ID: ff6b6aa54307
Revises: af8e44648542
Create Date: 2026-07-21 00:41:40.223532

"""
from alembic import op
import sqlalchemy as sa


revision = 'ff6b6aa54307'
down_revision = 'af8e44648542'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'mode')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('mode', sa.VARCHAR(length=16), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
